name: catalogo_polimorfico
description: Catálogo polimórfico con herencia, mixins y extensiones — proyecto semana 5 (Dart puro, sin Flutter)
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dev_dependencies:
  lints: ^5.0.0
